[versions]
agp="8.8.2"
activityCompose = "1.10.1"
composeThemeAdapter = "1.2.1"
compose = "1.7.8"
constraintlayout="2.2.1"
coreKtx="1.15.0"
easyvalidationCore="1.0.4"
firebaseBom="28.4.0"
hiltAndroid="2.55"
hiltNavigationFragment="1.2.0"
kotlin="2.1.10"
googleServices="4.3.14"
navigation ="2.8.8"
pagingCompose = "3.3.6"
workRuntimeKtx="2.10.0"
recyclerview="1.4.0"
coil="2.2.2"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
compose-theme-adapter = { module = "com.google.android.material:compose-theme-adapter", version.ref = "composeThemeAdapter" }

#Fragment Navigation
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }

#Hilt
androidx-hilt-navigation-fragment = { module = "androidx.hilt:hilt-navigation-fragment", version.ref = "hiltNavigationFragment" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }

#RecyclerView - Needed for Concat adapter
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }

#WorkManager
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }

#Compose
foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
material-icons={module="androidx.compose.material:material-icons-extended",version.ref="compose"}

#Easy Validation for validation of Input fields
easyvalidation-core = { module = "com.wajahatkarim:easyvalidation-core", version.ref = "easyvalidationCore" }

#Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-auth-ktx = { group = "com.google.firebase",name ="firebase-auth-ktx" }
firebase-firestore-ktx = { group = "com.google.firebase", name="firebase-firestore-ktx" }
firebase-functions-ktx = { group = "com.google.firebase", name = "firebase-functions-ktx" }
firebase-storage-ktx = { group = "com.google.firebase", name = "firebase-storage-ktx" }

#Pagination
androidx-paging-common-ktx = { module = "androidx.paging:paging-common-ktx", version.ref = "pagingCompose" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCompose" }

# Coil Image loading library to preview images from the cloud storage
coil-compose= {module = "io.coil-kt:coil-compose", version.ref="coil"}
coil= {module= "io.coil-kt:coil", version.ref="coil"}


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
hilt-android-gradle-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
google-services ={id = 'com.google.gms.google-services', version.ref="googleServices"}
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization-plugin = {id="org.jetbrains.kotlin.plugin.serialization", version.ref="kotlin"}
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-kapt={id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin"}
