plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-parcelize'
    id 'com.google.gms.google-services'
    id 'dagger.hilt.android.plugin'
    id 'org.jetbrains.kotlin.plugin.serialization' version '2.1.10'
    id 'kotlin-kapt'
    alias(libs.plugins.compose.compiler)
}

android {
    namespace 'com.sivakasi.papco.jobflow'
    compileSdk 35

    defaultConfig {
        applicationId "com.sivakasi.papco.jobflow"
        minSdk 24
        targetSdk 35
        versionCode 9
        versionName "1.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    android {
        // ...
        testOptions {
            unitTests.returnDefaultValues = true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures{
        viewBinding true
        compose true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = '11'
    }

    composeOptions {
        kotlinCompilerExtensionVersion "1.3.1"
    }

}

kapt {
    correctErrorTypes true
}

dependencies {

    def composeVersion="1.2.1"
    def paging_version = "3.1.1"
    def work_version = "2.10.0"

    implementation "org.jetbrains.kotlin:kotlin-stdlib:2.1.10"
    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.navigation:navigation-fragment-ktx:2.8.8'
    implementation 'androidx.navigation:navigation-ui-ktx:2.8.8'

    //Compose
    // Compose
    implementation libs.runtime
    implementation libs.ui
    implementation libs.foundation
    implementation libs.foundation.layout
    implementation libs.androidx.material
    implementation libs.androidx.runtime.livedata
    implementation libs.androidx.ui.tooling
    implementation libs.androidx.activity.compose
    implementation libs.compose.theme.adapter
    implementation libs.material.icons

    //WorkManager (For transforming and uploading the preview Images to firebase storage)
    implementation "androidx.work:work-runtime-ktx:$work_version"


    //Pagination
    //implementation libs.androidx.paging.runtime.ktx
    testImplementation libs.androidx.paging.common.ktx
    implementation libs.androidx.paging.compose


    //Recycler view (Needed for Concat Adapter)
    implementation "androidx.recyclerview:recyclerview:1.4.0"

    //Dagger Hilt
    implementation("androidx.hilt:hilt-navigation-fragment:1.2.0")
    implementation 'com.google.dagger:hilt-android:2.55'
    kapt 'com.google.dagger:hilt-compiler:2.55'
    androidTestImplementation  'com.google.dagger:hilt-android-testing:2.44'
    kaptAndroidTest 'com.google.dagger:hilt-compiler:2.55'
    testImplementation 'com.google.dagger:hilt-android-testing:2.44'
    kaptTest 'com.google.dagger:hilt-compiler:2.55'


    //Kotlin extensions for Fragment
    implementation "androidx.fragment:fragment-ktx:1.8.6"

    //Easy Validation for validation of Input fields
    implementation "com.wajahatkarim:easyvalidation-core:1.0.4"

    //Coroutines
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1'

    //Coil Image loading library to preview images from the cloud storage
    implementation "io.coil-kt:coil-compose:2.2.2"
    implementation "io.coil-kt:coil:2.2.2"

    //Firebase Libraries
    //When using the BoM, you don't specify versions in Firebase library dependencies
    implementation platform('com.google.firebase:firebase-bom:28.4.0')
    implementation 'com.google.firebase:firebase-firestore-ktx'
    implementation 'com.google.firebase:firebase-auth-ktx'
    implementation 'com.google.firebase:firebase-functions-ktx'
    implementation 'com.google.firebase:firebase-storage-ktx'

    //Zoomable ImageView to enable zooming and panning of Job Previews
    implementation 'com.jsibbold:zoomage:1.3.1'


    //Leak canary for leak detection
    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.7'

    //Algolia Stuff
    implementation "com.algolia:algoliasearch-client-kotlin:1.12.0"
    implementation "io.ktor:ktor-client-okhttp:1.6.7"

    testImplementation 'junit:junit:'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}