plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.hilt.android.gradle.plugin)
    alias(libs.plugins.google.services)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.serialization.plugin)
    alias(libs.plugins.kotlin.parcelize)
    alias(libs.plugins.kotlin.kapt)

}

android {
    namespace 'com.sivakasi.papco.jobflow'
    compileSdk 35

    defaultConfig {
        applicationId "com.sivakasi.papco.jobflow"
        minSdk 24
        targetSdk 35
        versionCode 9
        versionName "1.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    android {
        // ...
        testOptions {
            unitTests.returnDefaultValues = true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures{
        viewBinding true
        compose true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = '11'
    }

}

kapt {
    correctErrorTypes true
}

dependencies {

    implementation libs.androidx.core.ktx
    implementation libs.androidx.constraintlayout

    //Navigation
    implementation libs.androidx.navigation.fragment.ktx
    implementation libs.androidx.navigation.ui.ktx

    //Compose
    implementation libs.runtime
    implementation libs.ui
    implementation libs.foundation
    implementation libs.foundation.layout
    implementation libs.androidx.material
    implementation libs.androidx.runtime.livedata
    implementation libs.androidx.ui.tooling
    implementation libs.androidx.activity.compose
    implementation libs.compose.theme.adapter
    implementation libs.material.icons

    //WorkManager (For transforming and uploading the preview Images to firebase storage)
    implementation libs.androidx.work.runtime.ktx

    //Pagination
    testImplementation libs.androidx.paging.common.ktx
    implementation libs.androidx.paging.compose

    //Recycler view (Needed for Concat Adapter)
    implementation libs.androidx.recyclerview

    //Dagger Hilt
    implementation(libs.androidx.hilt.navigation.fragment)
    implementation libs.hilt.android
    kapt libs.hilt.compiler

    //Easy Validation for validation of Input fields
    implementation libs.easyvalidation.core

    //Coil Image loading library to preview images from the cloud storage
    implementation libs.coil.compose
    implementation libs.coil

    //Firebase Libraries
    //When using the BoM, you don't specify versions in Firebase library dependencies
    implementation platform(libs.firebase.bom)
    implementation libs.firebase.firestore.ktx
    implementation libs.firebase.auth.ktx
    implementation libs.firebase.functions.ktx
    implementation libs.firebase.storage.ktx

    //Zoomable ImageView to enable zooming and panning of Job Previews
    implementation 'com.jsibbold:zoomage:1.3.1'

    //Leak canary for leak detection
    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.7'

    //Algolia Stuff
    implementation "com.algolia:algoliasearch-client-kotlin:1.12.0"
    implementation "io.ktor:ktor-client-okhttp:1.6.7"

    testImplementation 'junit:junit:'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}